# Generated by Django 5.1.3 on 2024-11-06 21:37

import localflavor.br.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0005_customer_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cpf',
            field=localflavor.br.models.BRCPFField(default='123.456.789-09', max_length=14, unique=True, verbose_name='CPF'),
        ),
    ]
